NordicSemiconductor/zcbor

scripts/cddl_gen.py

use '==' when comparing literals to avoid warning

---

cmake/extensions.cmake
scripts/cddl_gen.py
tests/cbor_encode/test1_suit/CMakeLists.txt
tests/cbor_encode/test1_suit/src/main.c

between encoding and decoding.
This fixes #11

cddl_gen.py: Place typedefs in a separate file so they can be shared

---

cmake/extensions.cmake
zephyr/CMakeLists.txt

instead of add_custom_command, so it is run immediately when
called in Cmake.
It looks like this function will primarily be used once in a
while, not as a regular part of the build process. Making the
call happen immediately makes it less intrusive to add or
remove it from the build process, e.g. via a Cmake flag.

extensions.cmake: Convert cddl_gen call to execute_process

---

include/cbor_decode.h
include/cbor_encode.h
scripts/cddl_gen.py
src/cbor_decode.c
src/cbor_encode.c

It was unused as of now, but it can be useful to have it pointing
to the actual string when decoding, e.g. for calculating hash.
For encoding, use the string as input instead of the structure
if the string's value is not NULL.

Start using the string result for cbor encoded bstrs

---

include/cbor_decode.h
include/cbor_encode.h
scripts/cddl_gen.py
src/cbor_decode.c
src/cbor_encode.c

This was mostly the case, just fixed some stray errors.
Note: Not tested against checkpatch yet.

Format code to Zephyr standard

---

scripts/cddl_gen.py

It could be considered a nice thing to not break
80 cols when possible.

cddl_gen: reformat comment to stay within 80 columns

---

include/cbor_common.h
scripts/cddl_gen.py
src/cbor_decode.c

Make all calls to functions in cbor_decode.c restore the previous
state if they fail. This means the union_elem_code() call can
sometimes be dropped.

Apply small union improvement.

---

README.md
include/cbor_common.h
include/cbor_debug.h
include/cbor_decode.h
include/cbor_encode.h
scripts/cddl_gen.py
src/cbor_common.c
src/cbor_decode.c
src/cbor_encode.c
tests/cbor_decode/test.sh
tests/cbor_decode/test1_suit_old_formats/src/main.c
tests/cbor_decode/test2_suit/src/main.c
tests/cbor_decode/test3_simple/src/main.c
tests/cbor_decode/test5_strange/src/main.c
tests/cbor_encode/test.sh
tests/cbor_encode/test1_suit/src/main.c
tests/cbor_encode/test2_simple/src/main.c
tests/cbor_encode/test3_strange/src/main.c

Use uint32_t instead of size_t, except when doing pointer arithmetic.
Run tests on both native_posix and native_posix_64.

Add support for native_posix_64.

---

scripts/cddl_gen.py
tests/cbor_decode/test5_strange/CMakeLists.txt
tests/cbor_decode/test5_strange/src/main.c
tests/cbor_decode/test5_strange/strange.cddl
tests/cbor_encode/test3_strange/CMakeLists.txt
tests/cbor_encode/test3_strange/src/main.c
tests/cbor_encode/test3_strange/strange.cddl

Simple types without a list would be generated wrongly.
This fixes https://github.com/NordicSemiconductor/cddl-gen/issues/59

cddl_gen.py: Add support for entry types with no list

---

src/cbor_decode.c

The code could read past the payload buffer.

cbor_decode: Fix memory issues found by Simon Johansson

---

cddl_gen/cddl_gen.py
tests/cases/optional.cddl
tests/scripts/run_tests.py

Only attempt to flatten lists or tuples.
Without this, the script fails when the inner object does not have a
length.
Fixes #66

cddl_gen.py: DataTranslator: Fix flattening of lists

---

include/cbor_common.h
src/cbor_common.c
src/cbor_decode.c
src/cbor_encode.c

Rename FLAG_DISCARD to FLAG_CONSUME and restore_backup to process_backup.
Add docs to the flags and functions.

cbor_common: Rename and add docs to improve readability

---

README.md
cddl_gen/cddl_gen.py
include/cbor_common.h
src/cbor_common.c

entry_function() was used by the generated code to reduce duplication.
new_state() removes most of the same duplication, and is also useful
when not using the generated code.

cbor_common: Remove entry_function() and add new_state()

---

README.md
cddl_gen/cddl_gen.py
tests/cases/manifest2.cddl
tests/cases/manifest3.cddl
tests/cases/manifest9_simple.cddl
tests/cases/serial_recovery.cddl
tests/cases/strange.cddl

x*y is the correct syntax according to the spec.
x**y is still allowed for backwards compatibility.

Change quantifier syntax from x**y to x*y

---

cddl_gen/cddl_gen.py
tests/cases/strange.cddl
tests/cbor_decode/test5_strange/src/main.c
tests/cbor_encode/test3_strange/src/main.c

When there are three dots in the range (e.g. 1...5), the max is excluded
from the range, so that 1...5 is equivalent to 1..4

cddl_gen.py: Add support for ranges with three dots

---

cddl_gen/cddl_gen.py

cddl_gen.py: Allow backslashes before newlines in cddl files

---

src/cbor_decode.c

Add overflow check on string lengths.
Fix NULL-related assert.

cbor_decode.c: Fix any_decode()

---

zephyr/module.yml

The top level CMakeLists.txt has already been removed.
Make this change so a CMakeLists.txt can be placed inside the sdk-nrf
repo.

zephyr: module.yml: Change cmake-ext to True

---

.github/workflows/run-tests.yaml

They were both called "Run tests". Change to "Merge tests"
and "Release tests".

run-tests.yaml: Change names of test jobs

---

cddl_gen/cddl_gen.py

cddl_gen.py: Prevent a space in type declarations

---

zcbor/zcbor.py

The macro is added to generated code files.

zcbor.py: Add documentation for the DEFAULT_MAX_QTY macro

---

tests/cases/strange.cddl
tests/decode/test5_strange/CMakeLists.txt
tests/decode/test5_strange/src/main.c
zcbor/zcbor.py

Make them void instead.
Add regression test.

zcbor.py: Avoid creating functions with "None" result type

---

zcbor/zcbor.py

in the header file, the type file was included via full path instead of
just the name, which was inconvenient when creating files to be used by
others.

zcbor.py: Avoid #include-ing the full path of the type file

---

ARCHITECTURE.md
README.md
include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/decode/test5_strange/src/main.c
tests/encode/test1_suit/src/main.c
tests/encode/test2_simple/src/main.c
tests/encode/test3_strange/src/main.c
tests/unit/test1_unit_tests/src/main.c
zcbor/zcbor.py

- Rename zcbor_string_type_t to struct zcbor_string.
- Rename zcbor_state_backups_t to struct zcbor_state_constant.

Rename zcbor_string_typte_t and zcbor_state_backups_t

---

tests/cases/senml.cddl
tests/encode/test4_senml/CMakeLists.txt
tests/encode/test4_senml/prj.conf
tests/encode/test4_senml/src/main.c
tests/encode/test4_senml/testcase.yaml

zcbor\_\*\_encode() was used instead of zcbor\_\*\_put().
The bug was fixed earlier.
fixes #163

tests: encode: Add test4_senml to test a regression in code generation

---

include/zcbor_common.h

The tag values defined by the newest CBOR spec (RFC 8949).

zcbor_common.h: Add enum with some tag values

---

tests/scripts/run_tests.py
zcbor/zcbor.py

Needs to be parser.error() instead
Add test for the error print.

zcbor.py: Fix args.error() call

---

README.md
RELEASE_NOTES.md
include/zcbor_common.h
src/zcbor_common.c
src/zcbor_decode.c
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/decode/test5_corner_cases/testcase.yaml

Rename "Indeterminate length"  to "indefinite length" to match wording in the CBOR RFC.
Also refactor how the indefinite length state is kept.

Indefinite length arrays

---

src/zcbor_decode.c

zcbor_decode.c: Adapt define to cases where UINT_FAST32_MAX doesn't exist.

---

include/zcbor_common.h
include/zcbor_decode.h
src/zcbor_common.c
src/zcbor_decode.c
tests/unit/test1_unit_tests/src/main.c

This introduces functions to work with payloads that are split across multiple chunks.
This allows you to work with strings/lists/maps that have been split across the chunks, but simple values, like integers, booleans, list headers or string headers cannot be split.

String Fragments and split payloads

---

include/zcbor_encode.h

The function is often, indirectly, used to encode constant strings
and without the change compiler issues warnings on discarded
const qualifiers.

include: Add const to *ptr argument of cbor_tstr_encode_ptr

---

include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c

This means no error can occur during _new_state() which makes
could be scary if the error was not caught (the code would start
dereferencing NULL.

Make the C library handle missing constant_state

---

README.md
add_helptext.py
tests/scripts/run_tests.py

It has slightly different wording ("options" instead of "optional arguments").
Switch test to skip on versions < 3.10.
Change assert in add_helptext.py to the new wording.

Switch to Python 3.10 for the helptext generation.

---

include/zcbor_encode.h

Change affects zcbor_bstr_encode_ptr and zcbor_tstr_encode_ptr:
the in-call definition of structure works fine, but may cause
"taking address of rvalue" errors with some compiler configurations.
This commit moves the definition out of function invocation
and defines intermediate variable to prevent possible compilation
errors (or warnings).
To prevent errors like this (reported by C++ compilation):
```
modules/lib/zcbor/include/zcbor_encode.h:65:62: error: taking address of rvalue [-fpermissive]
65 |  return zcbor_tstr_encode(state, &(const struct zcbor_string){.value = ptr, .len = len});
|	
```

include: Define variables to avoid rvalue address errors

---

src/zcbor_decode.c

Commit 18f78c575f6f6df20c9c85f1260b12099d5ef67e
("zcbor.py: Remove unused types and members.")
introduced null handling for the result argument in
zcbor_bstr_start_decode().
However, in this implementation, if result is initially NULL,
then it will end up pointing to the location of a stack
variable allocated in a block which has gone out of scope
by the time it is used. This is unsafe; fix it.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

zcbor_bstr_start_decode: fix NULL result handling

---

include/zcbor_common.h
tests/unit/test1_unit_tests/src/main.c

Added zcbor_peek_error to allow checking error code without
directly accessing zcbor_state_t type object.

Add zcbor_peek_error for reading error value

---

tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test3_corner_cases/src/main.c
zcbor/zcbor.py

The indirection was missing in the generated code.
Add some tests.

zcbor.py: Fix bug when adding tagged items to larger types

---

include/zcbor_encode.h

Cosmetic correction of function parameter name.

include: Correct parameter name to align with other definitions

---

tests/cases/manifest2.cddl
tests/decode/test5_corner_cases/src/main.c
zcbor/zcbor.py

Brings back the optimization for decoding unions where all options start with a specific uint, e.g. an id. The optimization involves decoding the integer first, directly into the enum variable, and then decoding the union. This optimization was never applied to generated after a bug was introduced. This PR fixes that bug and also expands the feature to allow negative integers as well.

Fix the union uint optimization

---

RELEASE_NOTES.md
include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c

Add support for encoding/decoding size_t
The commit adds functions that allow to encode/decode size_t
with no need to know size_t real type.
In rare event where the size_t decoding/encoding functions can not
be generated, compilation warning will be issued and no function
definitions will be provided.
When architecture supports size_t encoding ZCBOR_SUPPORTS_SIZE_T
will be defined.

Add support for encoding/decoding size_t

---

RELEASE_NOTES.md
tests/cases/manifest3.cddl

Related to 695af474f1818cdecae40692b1401b83b1599cde
This was missed in CI because of change to twister in Zephyr.

tests: Fix an error in manifest3.cddl (collision with 'uri')

---

RELEASE_NOTES.md
scripts/requirements-base.txt

requirements.txt: Change PyYAML requirement from 6.0.0 to 5.4.1

---

include/zcbor_decode.h

This is similiar fix as it was done for encoder part in #218

decoder: define local variables to avoid rvalue address errors

---

.github/actions/install_zcbor/action.yaml
.github/actions/prepare_and_run_tests/action.yaml
.github/workflows/run-tests.yaml
tests/scripts/run_tests.py
tests/test.sh

Instead of manually dividing the twister tests via tags and asserts,
divide by platform.
Asserts are still handled manually instead of adding an "asserts" variant
to all testcase.yaml files.
Create a new action "install_zcbor", to support the use case of installing
without running tests.
Add support for the zephyr toolchain to run tests on qemu
Print twister command before executing it
Do codestyle testing as part of Python unittesting

.github: Refactor Github action to use more of strategy: matrix

---

.github/actions/prepare_and_run_tests/action.yaml
README.md
add_helptext.py
tests/decode/test1_suit_old_formats/CMakeLists.txt
tests/decode/test2_suit/CMakeLists.txt
tests/decode/test3_simple/CMakeLists.txt
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test7_suit9_simple/CMakeLists.txt
tests/decode/test8_suit12/CMakeLists.txt
tests/decode/test9_manifest14/CMakeLists.txt
tests/encode/test1_suit/CMakeLists.txt
tests/encode/test2_simple/CMakeLists.txt
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test4_senml/CMakeLists.txt
tests/scripts/run_tests.py
zcbor/zcbor.py

zcbor.py: Refactor CLI to add 'verify' and put all options after keyword
Added the 'verify' keyword instead of using 'convert' with no output.
'convert' now requires an output.
All options now appear after the keyword. I.e. code/verify/convert are
always first when invoking zbor.
Also, do a slight refactor of the README

CLI refactor

---

include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h

Since it causes include-order problems in Zephyr builds. ARRAY_SIZE() in zephyr/sys/util.h is not encased in #ifndef. Encasing zcbor's ARRAY_SIZE in #ifdef __ZEPHYR__ causes problems in zcbor's tests because util.h gives warnings under -Wconversion (which is used in zcbor tests).

zcbor_common.h: Rename ARRAY_SIZE to ZCBOR_ARRAY_SIZE

---

include/zcbor_common.h
src/zcbor_decode.c
src/zcbor_encode.c

For situations where the 'state' variable is available, so the assertion can be reported as ZCBOR_ERR_ASSERTION.
This prevents cases where an assert hides where it came from because it did not update the error variable.

zcbor_common.h: Add new zcbor_assert_state() macro

---

include/zcbor_decode.h
src/zcbor_decode.c
tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test3_corner_cases/src/main.c
zcbor/zcbor.py

When a union contains another type, which is disambiguated, but which
will be decoded with its own function, the first integer would be
attempted decoded twice, once to populate the choice enum, and once
in the type's own function. This change reports such cases as
not disambiguated, so the union_int optimization won't be applied.
Later, it could be possible to make it possible to apply the union_int
optimization to these cases as well, but that would require more work,
possibly generating two variants of the function, one with and one
without decoding the first integer.
Add tests, splitting the UnionInt into two versions, one where the
optitmization is applied, and one where it's not.
The following is needed for the …

zcbor.py: Fix bug where the union_int optimization decodes twice

---

include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c

Analogous to the 'int' variety which already exists. Add test.

C libraries: Add new APIs zcbor_uint_(encode/decode)

---

include/zcbor_common.h
include/zcbor_encode.h
include/zcbor_tags.h
setup.py
zcbor/zcbor.py

www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
I didn't add all tags from the list. I only added tags from published RFCs (not drafts), and I excluded some that I'm not familiar with and some which are repetitive, to not crowd the list. If we want to add all tags, we might want to make a separate file for the tags enum.
Fixes #274

zcbor_common.h: Add more tags from the IANA list

---

tests/decode/test5_corner_cases/src/main.c
tests/encode/test2_simple/src/main.c
zcbor/zcbor.py

Remove unneeded includes from header files for easier mocking. Some additional cleanup

zcbor.py: Clean up #includes in generated files

---

.github/workflows/run-tests.yaml
include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_decode.c
src/zcbor_encode.c
tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test3_corner_cases/src/main.c
tests/scripts/test_zcbor.py
tests/unit/test1_unit_tests/src/main.c

C libraries: Rename prim/primitive to simple
Which is what it's called in RFC8949.
Includes exposing new APIs: zcbor_simple_(encode/put/decode/expect)
Add some tests for the new APIs.
Note: The use of "Prim" in zcbor.py is different and is not touched by
this change.

Add support for simple values and rename "prim" to "simple"

---

README.md
zcbor/zcbor.py

the --version keyword was moved when everything was moved so that 'code' and 'verify' come first.

zcbor.py: Bring back 'zcbor --version'

---

README.md
samples/pet/CMakeLists.txt
samples/pet/include/pet_decode.h
samples/pet/include/pet_encode.h
samples/pet/include/pet_types.h
samples/pet/pet.cmake
samples/pet/src/pet_decode.c
samples/pet/src/pet_encode.c
tests/decode/test3_simple/CMakeLists.txt
tests/scripts/test_repo_files.py
zcbor/zcbor.py

These can be used for copyrights.

zcbor.py: Add support for file headers.

---

README.md
tests/scripts/test_repo_files.py

Since asserts happened in a thread, they did not cause the test to fail.
Do assert in main thread instead.

test_repo_file.py: Fix link testing so asserts are caught 

---

src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test1_unit_tests/CMakeLists.txt

Build with these in unit test 1.
Note that generated code has multiple problems when building with these flags that are difficult to resolve, so are not covered by this.
Fixes #299

src: Make the zcbor source files compile with -Wall and -Wconversion

---

include/zcbor_common.h
src/zcbor_common.c
src/zcbor_decode.c
tests/unit/test1_unit_tests/src/main.c

More correct, and smaller code size.
Add test.

zcbor_decode.c: Refactor zcbor_any_skip()

---

include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
samples/pet/include/pet_types.h
src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/src/main.c
tests/unit/test1_unit_tests/src/main.c
tests/unit/test2_cpp/src/main.cpp
zcbor/zcbor.py

Because it's more concise, more descriptive, since most of the uses are counts.
The "present" variable has been changed to bool instead.

Change all uint_fast32_t usage to use size_t instead

---

samples/pet/include/pet_types.h
samples/pet/src/main.c
samples/pet/src/pet_decode.c
samples/pet/src/pet_encode.c
tests/decode/test1_suit_old_formats/src/main.c
tests/decode/test2_suit/src/main.c
tests/decode/test3_simple/src/main.c
tests/decode/test5_corner_cases/src/main.c
tests/decode/test7_suit9_simple/src/main.c
tests/decode/test9_manifest14/src/main.c
tests/encode/test1_suit/src/main.c
tests/encode/test2_simple/src/main.c
tests/encode/test3_corner_cases/src/main.c
tests/encode/test4_senml/src/main.c
tests/fuzz/fuzz_manifest12.c
tests/scripts/test_zcbor.py
zcbor/zcbor.py

in generated code
See changes in zcbor.py. The rest of the changes are renaming tests.
Fixes #294 and #295

Avoid leading and trailing as well as repeated underscores

---

include/zcbor_common.h
samples/pet/src/pet_decode.c
samples/pet/src/pet_encode.c
src/zcbor_common.c
zcbor/zcbor.py

This reduces the code size when multiple entry functions are defined.

zcbor_common: Add a zcbor_entry_function helper

---

.github/actions/prepare_and_run_tests/action.yaml
.github/workflows/run-tests.yaml

Update Zephyr SDK version, and fix Zephyr version to a specific commit, so that the CI doesn't suddenly break because of changes in Zephyr.

Zephyr versions

---

src/zcbor_decode.c
src/zcbor_encode.c
tests/decode/test2_suit/CMakeLists.txt
tests/decode/test5_corner_cases/CMakeLists.txt
tests/unit/test1_unit_tests/CMakeLists.txt

C implicit promotion rules will want to make floats into doubles very easily. Fix the constants that were defined as doubles.
Related PR: https://github.com/zephyrproject-rtos/zephyr/pull/57154

 zcbor_encode, zcbor_decode: fix double promotion warnings

---

include/zcbor_encode.h
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c
tests/unit/test2_cpp/src/main.cpp
zcbor/zcbor.py

and only use zcbor_present_decode() in complex cases. This saves footprint.
Then remove zcbor_present_encode().

zcbor.py: Don't use zcbor_present_encode()

---

include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_decode.c
src/zcbor_encode.c

zcbor_encode, zcbor_decode: Move inline functions from header files

---

include/zcbor_encode.h
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c
tests/unit/test2_cpp/src/main.cpp
zcbor/zcbor.py

Add zcbor_tag_put() which takes a value argument.

zcbor_encode: Change zcbor_tag_encode to take a pointer argument

---

include/zcbor_common.h
src/zcbor_decode.c

And rename to include a ZCBOR_ prefix.
This allows them to be used in other files.

zcbor_decode.c: Move MAJOR_TYPE() and ADDITIONAL() macros to zcbor_common.h

---

include/zcbor_common.h
src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test3_float16/src/main.c

Create new functions zcbor_float16_to_32() and zcbor_float32_to_16() in zcbor_common.c and use these in the decoding/encoding functions.
Adapt float16 test to use the new functions directly for the lengthiest test.

src: Abstract float16 conversion and move it to zcbor_common.c

---

include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_decode.c
src/zcbor_encode.c

Attempt to make better groupings of functions, and add shared docs for similar functions wherever possible. Also generally improve the docs.
Header file line count goes down significantly.
This is done in anticipation of adding a new class of functions, which should be possible with minimal clutter in the files.

include: Rearrange and improve zcbor_decode.h and zcbor_encode.h

---

samples/pet/include/pet_types.h
samples/pet/src/main.c
samples/pet/src/pet_decode.c
samples/pet/src/pet_encode.c
tests/decode/test1_suit_old_formats/src/main.c
tests/decode/test2_suit/src/main.c
tests/decode/test3_simple/src/main.c
tests/decode/test5_corner_cases/src/main.c
tests/decode/test9_manifest14/src/main.c
tests/encode/test1_suit/src/main.c
tests/encode/test2_simple/src/main.c
tests/encode/test3_corner_cases/src/main.c
tests/encode/test4_senml/src/main.c
zcbor/zcbor.py

This is to make them different from the data elements they refer to, since in C++ they occupy the same namespace, causing compilation errors.
Most of the patch is changing samples and tests to match the new naming.
Fixes #314 and https://github.com/zephyrproject-rtos/zephyr/issues/54092

zcbor.py: Change name of generated choice enum members to add a '_c'

---

include/zcbor_decode.h
src/zcbor_decode.c
tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
zcbor/zcbor.py

and make sure multi_(en|de)code always uses functions with pointer arguments. This is to avoid problems with register alignment or other issues in the calling conventions of pointer arguments vs. other arguments. E.g. on cortex-m a uint64 as the 2nd argument will be aligned to registers R2 and R3 instead of R1, while a uint32 or a pointer will use R1.
Add test that fails on the previous implementation and is fixed by this change.

zcbor_decode: Add _pexpect() functions

---

zcbor/zcbor.py

When run on windows, zcbor.py would mix / and \ in cmake files.
Cmake uses only / internally, even on Windows, so make zcbor.py
generate cmake files with only /.

zcbor.py: Generate cmake files with linux paths on Windows

---

README.md
RELEASE_NOTES.md
include/zcbor_common.h
include/zcbor_decode.h
samples/hello_world/src/main.c
src/zcbor_common.c
src/zcbor_decode.c
src/zcbor_encode.c
tests/cmake/test_template.cmake
tests/decode/test3_simple/src/main.c
tests/decode/test5_corner_cases/src/main.c
tests/unit/test1_unit_tests/src/main.c
tests/unit/test1_unit_tests/testcase.yaml
tests/unit/test2_cpp/src/main.cpp
tests/unit/test3_float16/src/main.c

C library: Add support for searching for elements in a map.
Map elements should per the spec be assumed to appear in arbitrary order.
This PR brings some new functions to zcbor_decode, called
zcbor_unordered_map_*().
These functions can be used to search for keys within a map.
The existing map decoding functions work like before.
This PR adds some optional functionality when it comes to keeping track
of which elements in a map have been found. The new functionality can
be enabled with ZCBOR_MAP_SEARCH_FLAGS.

Add support for searching for elements in a map.

---

README.md
include/zcbor_common.h
src/zcbor_decode.c
tests/decode/test9_manifest14/testcase.yaml
tests/unit/test1_unit_tests/src/main.c
tests/unit/test1_unit_tests/testcase.yaml
zcbor/zcbor.py

When ZCBOR_CANONICAL is enabled.

zcbor_decode: Add validation that data follows canonical CBOR rules

---

src/zcbor_decode.c

This can happen when ZCBOR_STOP_ON_ERROR is enabled.

zcbor_decode.c: Fix "'num_decode' may be used uninitialized"

---

include/zcbor_common.h

For the case when it is not available, and the weak implementation in zcbor_common is used.

zcbor_common.h: Add forward declaration for strnlen()

---

samples/pet/src/pet_decode.c
tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
zcbor/zcbor.py

The conversion happened prematurely, and caused errors when the value
was compared to ints. Refactor so the conversion happens at the latest
possible point. Add test.
Fixes #387

Fix conversion of UINT8_MAX etc.

---

tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test3_corner_cases/src/main.c
zcbor/zcbor.py

This is a bug in the union_int optimization. In maps, the optimization refers to the key, but was propagated to the value as well, so that in some cases, if the key was optimized away, the value was erroneously optimized away as well.
Thanks to Pete Johanson for finding and debugging this issue!
Fixes #398

zcbor.py: Fix a bug where some decoding function were not called

---

src/zcbor_encode.c

to avoid decrement + increment

zcbor_encode.c: Move trace during value_encode

---

.github/workflows/run-tests.yaml

that are used to run the CI tests.
Zephyr 3.6.0-rc2 -> 3.6.0
Zephyr SDK 0.16.4 -> 0.16.5

run-tests.yaml: Update versions of Zephyr and Zephyr SDK

---

tests/cmake/test_template.cmake
tests/decode/test5_corner_cases/src/main.c
tests/encode/test2_simple/src/main.c
tests/encode/test3_corner_cases/src/main.c
tests/encode/test4_senml/src/main.c
tests/include/common_test.h

instead of duplicating in all tests

tests: Move LIST() and MAP() macros to dedicated header file

---

.github/workflows/run-tests.yaml
tests/be_test.sh
tests/decode/test1_suit_old_formats/testcase.yaml
tests/decode/test2_suit/testcase.yaml
tests/decode/test3_simple/testcase.yaml
tests/decode/test5_corner_cases/testcase.yaml
tests/decode/test7_suit9_simple/testcase.yaml
tests/decode/test8_suit12/testcase.yaml
tests/decode/test9_manifest14/testcase.yaml
tests/encode/test1_suit/testcase.yaml
tests/encode/test2_simple/testcase.yaml
tests/encode/test3_corner_cases/testcase.yaml
tests/encode/test4_senml/testcase.yaml
tests/test.sh
tests/unit/test1_unit_tests/testcase.yaml
tests/unit/test2_cpp/testcase.yaml
tests/unit/test3_float16/testcase.yaml

Updates the board name used by tests to account for the change when moving to hwmv2 in zephyr

tests: Update mps2 board name

---

MIGRATION_GUIDE.md
tests/scripts/test_versions.py

To be updated at least with each minor version.
Add release test for the version number.
Add entries for changes so far.
Populate the 0.8.0 entry with text from Zephyr migration guide.

MIGRATION_GUIDE.md: Add a migration guide file

---

tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/src/main.c
zcbor/zcbor.py

For positive integers, the value is part of the name, but this was missed for negative integers. This fixes it.

zcbor.py: Fix bug where NINT literals were not given unique names

---

scripts/requirements-test.txt
tests/cases/corner_cases.cddl
tests/decode/test5_corner_cases/CMakeLists.txt
tests/decode/test5_corner_cases/src/main.c
tests/encode/test3_corner_cases/CMakeLists.txt
tests/encode/test3_corner_cases/src/main.c
zcbor/zcbor.py

- Two elements with different names referring to the same value were generated
- Sometimes a value was attempted dereferenced as result->somevalue, but it should have been just result.
This introduces the concept of delegated types, where the a type takes on the C type of one of its children. This was handled via a shortcut that failed for certain corner cases.
This also refactors the "skip" mechanism which was inconsistently referring to itself or its parent, as part of the shortcut mentioned above.
Add tests

zcbor.py: Fix a few bugs in code generation to do with dereferencing

---

zcbor/zcbor.py

The solution using ?R (regression) didn't work when the regexes were put together into one regex, because ?R implicitly references the "whole regex", which becomes something different when merging many separate regexes into one. Instead use subroutines which are more general and can be used to implement ?R. Use differently named subroutines so they are unambiguous no matter which regex they are a part of.
Fixes #440

zcbor.py: Fix range_types when used together in range_types_regexes

---

include/zcbor_common.h
src/zcbor_decode.c
tests/decode/test5_corner_cases/src/main.c
tests/decode/test5_corner_cases/testcase.yaml
tests/unit/test1_unit_tests/src/main.c

Floats with leading 0s were rejected because the decoder wrongly assumed they could have been encoded with fewer bytes.
Exclude floats from this check and add some tests

zcbor_decode: Fix a bug with enforce_canonical (ZCBOR_CANONICAL) + floats

---

src/zcbor_decode.c
src/zcbor_encode.c
tests/unit/test1_unit_tests/src/main.c

As per RFC8949 sec 3.3.
Simple values less than 24 MUST be encoded in the additional information. Simple values 24 to 31 inclusive are unused.

Enforce encoding rules for simple values

---

MIGRATION_GUIDE.md
scripts/update_version.py

when updating RELEASE_NOTES and MIGRATION_GUIDE.
Instead use specified boilerplate when constructing the new entry.
Fix duplicated MIGRATION_GUIDE entry.

update_version.py: Don't copy previous entry

---

.github/workflows/run-tests.yaml
tests/decode/test1_suit_old_formats/testcase.yaml
tests/decode/test2_suit/testcase.yaml
tests/decode/test3_simple/testcase.yaml
tests/decode/test5_corner_cases/testcase.yaml
tests/decode/test7_suit9_simple/testcase.yaml
tests/decode/test8_suit12/testcase.yaml
tests/decode/test9_manifest14/testcase.yaml
tests/encode/test1_suit/testcase.yaml
tests/encode/test2_simple/testcase.yaml
tests/encode/test3_corner_cases/testcase.yaml
tests/encode/test4_senml/testcase.yaml
tests/unit/test1_unit_tests/testcase.yaml
tests/unit/test2_cpp/testcase.yaml
tests/unit/test3_float16/testcase.yaml

They have been deprecated, and support is removed in Zephyr.
https://github.com/zephyrproject-rtos/zephyr/pull/82404

tests: Update testcase.yaml files to not use space-separated lists

---

src/zcbor_decode.c

zcbor_decode.c: Remove unused variable to avoid GCC warning

---

__init__.py
scripts/add_helptext.py
scripts/black.sh
scripts/regenerate_samples.py
scripts/requirements-test.txt
scripts/update_version.py
tests/decode/test5_corner_cases/floats.py
tests/scripts/test_repo_files.py
tests/scripts/test_versions.py
tests/scripts/test_zcbor.py
tests/unit/test3_float16/floats.py
zcbor/zcbor.py

Modify the TestCodestyle test to use black instead of pycodestyle, to avoid disagreements in formatting between the two.
Add black.sh for quickly formatting the codebase.

Reformat all python files with black

---

src/zcbor_common.c

When running with ubsan (that is, with -fsanitize=undefined flags), there's an error from zcbor/src/zcbor_common.c:386:
runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
Fix this by using unsigned integer literal when forming abs_input in zcbor_float32_to_16.

zcbor_float32_to_16: fix ubsan error

---

src/zcbor_decode.c
tests/unit/test1_unit_tests/src/main.c

If zcbor_elem_processed() was called immediately upon entering an unordered map, get_current_index() would return SIZE_MAX.
This would be caught and result in a ZCBOR_ERR_MAP_FLAGS_NOT_AVAILABLE error.
This commit fixes get_current_index(), but also errors early in this case.
The returned error is now ZCBOR_ERR_MAP_MISALIGNED

zcbor_decode.c: Gracefully handle calling elem_processed early

---

zcbor/zcbor.py

Make it more concise, it doesn't need 5 separate regexes.

zcbor.py: Refactor parsing of "float16", "float32-64" etc

---

MIGRATION_GUIDE.md
include/zcbor_common.h
include/zcbor_decode.h
include/zcbor_encode.h
src/zcbor_common.c
src/zcbor_decode.c
tests/unit/test1_unit_tests/src/main.c

for casting function pointers.

zcbor_common.h: Introduce the ZCBOR_CAST_FP() macro

---

README.md
tests/scripts/test_zcbor.py
zcbor/zcbor.py

zcbor.py: Support canonical encoding when converting to CBOR in script

---

tests/scripts/test_performance.py
zcbor/zcbor.py

Avoid many different instances of regenerating the same string or data structure for every call.
Allow using DataTranslator without decoding, since Decoding into the NamedTuple-based format has a signinficant performance penalty.
Addresses #471

zcbor.py: Performance improvements in DataTranslator

---

tests/scripts/doc_fail_cases/fail1.md
tests/scripts/doc_fail_cases/fail2.md
tests/scripts/doc_fail_cases/fail3.md
tests/scripts/test_repo_files.py
zcbor/zcbor.py

Use backoff timer if receiving a 429 error (because of changes in Github).
Only check links once if they appear multiple times across doc files.
Only check doc files that have been changed.

test_repo_files: Refactor checking of links in docs
