NordicSemiconductor/zcbor

- scripts/cddl_gen.py
- src/cbor_decode.c
Fix comments from https://github.com/JuulLabs-OSS/mcuboot/pull/660
> Time header

- LICENSE
Just for completeness also add the Apache LICENSE file to the root directory (The SPDX headers already look good!).
> Add main LICENSE file

- scripts/cddl_gen.py
A little bit simpler to understand implementation with use of comma
operator.
> cddl_gen.py: val_or_null simplification and improved description

- .github/workflows/run-tests.yaml
- tests/cbor_decode/test.sh
- tests/cbor_encode/test.sh
- tests/cbor_encode/test3_strange/src/main.c
Add an initial workflow to run cbor_decode and cbor_encode tests on the CI and update scripts to exit on error.
> add initial GH action testing

- README.md
Add --oc and --oh arguments which are mandatory.
Fixes #13
> README: Fix python example

- scripts/cddl_gen.py
> Use uint value as enum value (if all options have a uint value)

- cmake/extensions.cmake
generate_cddl() can be used for more flexibility.
> cmake: Refactor target_cddl_source() into two functions

- include/cbor_common.h
- scripts/cddl_gen.py
- tests/cbor_decode/test1_suit_old_formats/src/main.c
- tests/cbor_decode/test2_suit/src/main.c
- tests/cbor_decode/test3_simple/src/main.c
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test7_suit9_simple/src/main.c
- tests/cbor_encode/test1_suit/src/main.c
> Add decoded size as output from generated decoding functions

- scripts/cddl_gen.py
> cddl_gen.py: Fix function name printing

- README.md
- cmake/extensions.cmake
- scripts/cddl_gen.py
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_encode/test3_strange/CMakeLists.txt
- tests/cbor_encode/test3_strange/src/main.c
> cddl_gen.py: Allow default_maxq to be set via command line

- include/cbor_common.h
- scripts/cddl_gen.py
- src/cbor_common.c
- tests/cbor_decode/test1_suit_old_formats/CMakeLists.txt
- tests/cbor_decode/test3_simple/CMakeLists.txt
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_decode/test7_suit9_simple/CMakeLists.txt
- tests/cbor_encode/test1_suit/CMakeLists.txt
- tests/cbor_encode/test2_simple/CMakeLists.txt
- tests/cbor_encode/test3_strange/CMakeLists.txt
Add generalized entry_function implementation to save binary space and reduce LoCs in generated code.
> Entry function refactor

- .github/workflows/run-tests.yaml
- include/cbor_common.h
- include/cbor_decode.h
- include/cbor_encode.h
- scripts/cddl_gen.py
- src/cbor_common.c
- src/cbor_decode.c
- src/cbor_encode.c
> remove p_ prefx

- scripts/cddl_gen.py
- tests/cbor_decode/test1_suit_old_formats/src/main.c
- tests/cbor_decode/test2_suit/src/main.c
- tests/cbor_decode/test3_simple/src/main.c
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test7_suit9_simple/src/main.c
- tests/cbor_encode/test1_suit/src/main.c
- tests/cbor_encode/test2_simple/src/main.c
- tests/cbor_encode/test3_strange/src/main.c
Unit tests must be updated (:
Fixes #41 
> start work on removing typedefs

- cmake/extensions.cmake
- scripts/cddl_gen.py
- tests/cbor_decode/test.sh
- tests/cbor_encode/test.sh
Lots of moving things around. No functional changes.
> Refactor to facilitate adding python decoding support

- .github/workflows/run-tests.yaml
- scripts/cddl_gen.py
- tests/cbor_decode/test1_suit_old_formats/CMakeLists.txt
- tests/cbor_decode/test2_suit/CMakeLists.txt
- tests/cbor_decode/test3_simple/CMakeLists.txt
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_decode/test7_suit9_simple/CMakeLists.txt
- tests/cbor_encode/test1_suit/CMakeLists.txt
- tests/cbor_encode/test2_simple/CMakeLists.txt
- tests/cbor_encode/test3_strange/CMakeLists.txt
- tests/test.sh
> PEP8 fixes ++

- cmake/extensions.cmake
- include/cbor_common.h
- tests/cbor_decode/test4_serial_recovery/test.sh
Error out early when cddl_gen.py fails
Update board names
Fix dox alignment
> Various small fixes

- include/cbor_encode.h
- src/cbor_encode.c
> cbor_encode: Add _put option for non-pointer values

- ARCHITECTURE.md
- README.md
- cmake/extensions.cmake
- scripts/cddl_gen.py
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_encode/test3_strange/CMakeLists.txt
- tests/scripts/run_tests.py
> Architecture document

- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test5_strange/strange.cddl
- tests/cbor_encode/test3_strange/src/main.c
- tests/cbor_encode/test3_strange/strange.cddl
I wanted to check that this worked, so I made a test, and it did. No reason not to keep it :).
> Add test for multiple literal uints.

- include/cbor_debug.h
- include/cbor_decode.h
- include/cbor_encode.h
- scripts/cddl_gen.py
- src/cbor_decode.c
- src/cbor_encode.c
- tests/cbor_decode/test1_suit_old_formats/src/main.c
- tests/cbor_decode/test2_suit/src/main.c
- tests/cbor_decode/test3_simple/src/main.c
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test7_suit9_simple/src/main.c
- tests/cbor_encode/test1_suit/src/main.c
- tests/cbor_encode/test2_simple/src/main.c
- tests/cbor_encode/test3_strange/src/main.c
Look at the individual commits.
> Various small improvements

- .gitignore
- scripts/cddl_gen.py
Fix some duplication.
Refactor single_func_prim into two functions.
Add playground* to gitignore so these files can be created for
debugging purposes.
No functional change.
> Various small improvements/refactoring

- scripts/cddl_gen.py
> add yaml to obj function

- setup.py
> setup.py: Update to version 0.2.0

- cddl_gen/cddl_gen.py
- cmake/extensions.cmake
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test5_strange/strange.cddl
- tests/cbor_encode/test3_strange/CMakeLists.txt
- tests/cbor_encode/test3_strange/src/main.c
- tests/cbor_encode/test3_strange/strange.cddl
> Fix parsing of ':' together with '/'

- src/cbor_encode.c
- tests/cbor_decode/test5_strange/CMakeLists.txt
- tests/cbor_decode/test5_strange/src/main.c
- tests/cbor_decode/test5_strange/strange.cddl
- tests/cbor_encode/test3_strange/CMakeLists.txt
- tests/cbor_encode/test3_strange/src/main.c
- tests/cbor_encode/test3_strange/strange.cddl
expands on https://github.com/NordicSemiconductor/cddl-gen/pull/78
> Fix value length logic in cbor_decode.c

- cddl_gen/cddl_gen.py
Add it as an addendum to the version.
> cddl_gen: Allow adding the current git sha to generated file headers.

- setup.py
- tests/scripts/run_tests.py
> setup.py: Change entry point for the script from cddl_gen to cddl-gen

- cddl_gen/cddl_gen.py
- tests/cases/strange.cddl
> Various cleanup

- include/cbor_common.h
- src/cbor_decode.c
> src: Fix types for printing verbose info

- cddl_gen/cddl_gen.py
> fixup! cddl_gen: Allow passing multiple cddl files.

- cddl_gen/cddl_gen.py
- tests/cbor_decode/test9_manifest14/CMakeLists.txt
- tests/cbor_decode/test9_manifest14/prj.conf
- tests/cbor_decode/test9_manifest14/src/main.c
- tests/cbor_decode/test9_manifest14/testcase.yaml
- tests/scripts/run_tests.py
plus another small fix for .bits
Signature check code is commented out until I have clarified some things about the signature checking procedure.
> Manifest14 tests (Python and C)

- RELEASE_NOTES.md
> RELEASE_NOTES.md: Add initial release notes for v0.3.0

- .github/workflows/run-tests.yaml
- cddl_gen/cddl_gen.py
- setup.py
- tests/fuzz/CMakeLists.txt
- tests/fuzz/test-afl.sh
- tests/scripts/run_tests.py
Non-release-related changes in a separate PR.
> Cleanup ahead of 0.3.0

- README.md
> README: Reorder and add a new introduction

- zcbor/zcbor.py
> zcbor.py: Add help text for the --output-cmake cmdline option

- src/zcbor_decode.c
- src/zcbor_encode.c
> Clean up static function names.

- RELEASE_NOTES.md
> RELEASE_NOTES.md: Add section for zcbor 0.3.99

- include/zcbor_common.h
- src/zcbor_decode.c
- src/zcbor_encode.c
- tests/cmake/test_template.cmake
- tests/decode/test1_suit_old_formats/CMakeLists.txt
- tests/decode/test2_suit/CMakeLists.txt
- tests/decode/test3_simple/CMakeLists.txt
- tests/decode/test5_strange/CMakeLists.txt
- tests/decode/test5_strange/src/main.c
- tests/decode/test7_suit9_simple/CMakeLists.txt
- tests/decode/test8_suit12/CMakeLists.txt
- tests/decode/test9_manifest14/CMakeLists.txt
- tests/encode/test1_suit/CMakeLists.txt
- tests/encode/test2_simple/CMakeLists.txt
- tests/encode/test2_simple/src/main.c
- tests/encode/test3_strange/CMakeLists.txt
- tests/encode/test3_strange/src/main.c
- tests/test.sh
- tests/unit/test1_unit_tests/CMakeLists.txt
- tests/verbose_test.sh
- zcbor/zcbor.py
> Build with -Wpedantic and -Wconversion

- .github/workflows/run-tests.yaml
- setup.py
- tests/scripts/run_tests.py
Add install test on Windows.
Fixes #161
> setup.py: Fix windows install, catch OSError in absolute_links()

- tests/scripts/run_tests.py
> run_tests.py: Bugfix for the test_map_bstr test case on Windows

- README.md
> README: Add sentence about endianness.

- .github/workflows/run-tests.yaml
- include/zcbor_common.h
- src/zcbor_encode.c
- tests/cmake/test_template.cmake
- tests/verbose_test.sh
> Control asserts separately from verbose (add ZCBOR_ASSERT option)

- README.md
- add_helptext.py
- tests/scripts/run_tests.py
- zcbor/zcbor.py
add_helptext.py is used for this, and should be used later to update.
> README.md: Add copy of zcbor helptext to the README

- zcbor/zcbor.py
This prevents a compiler warning when dealing with 64-bit limits
Fixes https://github.com/NordicSemiconductor/zcbor/issues/190
> zcbor.py: Add suffix for values larger than 32-bits

- tests/cases/corner_cases.cddl
- tests/decode/test5_corner_cases/src/main.c
- tests/encode/test3_corner_cases/src/main.c
Add tests for changes in #191.
> tests: corner_cases: Add test for uint .size 8

- README.md
- tests/encode/test1_suit/CMakeLists.txt
- tests/scripts/run_tests.py
- zcbor/zcbor.py
Allow specifying both --decode and --encode.
Adapt encode/test1 to use this.
> zcbor.py: Allow generating encoding and decoding code in one call

- .github/actions/prepare_and_run_tests/action.yaml
- .github/workflows/run-tests.yaml
- tests/cmake/test_template.cmake
- tests/decode/test1_suit_old_formats/CMakeLists.txt
- tests/decode/test2_suit/CMakeLists.txt
- tests/decode/test3_simple/CMakeLists.txt
- tests/decode/test5_corner_cases/CMakeLists.txt
- tests/decode/test5_corner_cases/src/main.c
- tests/decode/test7_suit9_simple/CMakeLists.txt
- tests/decode/test8_suit12/CMakeLists.txt
- tests/decode/test9_manifest14/CMakeLists.txt
- tests/encode/test1_suit/CMakeLists.txt
- tests/encode/test2_simple/CMakeLists.txt
- tests/encode/test3_corner_cases/CMakeLists.txt
- tests/unit/test1_unit_tests/CMakeLists.txt
The action prevents duplication in the YAML.
The action uses input values to choose what to do.
>  .github: Divide merge-test into 5 using a local custom action

- RELEASE_NOTES.md
> RELEASE_NOTES: Add entries for upcoming release.

- tests/cases/corner_cases.cddl
- tests/decode/test5_corner_cases/CMakeLists.txt
- tests/decode/test5_corner_cases/src/main.c
- tests/encode/test3_corner_cases/CMakeLists.txt
- tests/encode/test3_corner_cases/src/main.c
- zcbor/zcbor.py
> zcbor.py: Fix missing size check for repeated bstrs with their own type

- src/zcbor_encode.c
- tests/unit/test1_unit_tests/src/main.c
This applies to builds with ZCBOR_CANONICAL enabled.
Also change the memmove() call to something equivalent.
> zcbor_encode.c: Make the code handle max_num being too small

- .github/actions/prepare_and_run_tests/action.yaml
- .github/workflows/run-tests.yaml
- setup.py
- tests/scripts/run_tests.py
- zcbor/zcbor.py
Run python tests on all Python versions on all PRs
Run unit tests on all Python versions during release testing.
> .github: Run tests on all Python versions from 3.7 to 3.10

- scripts/requirements-test.txt
- tests/scripts/run_tests.py
> tests: scripts: Enable and fix test for signature check of manifest

- scripts/requirements-base.txt
> scripts: Update pip requirements to newest versions

- zcbor/zcbor.py
> zcbor.py: Disallow list entries with keys

- README.md
- RELEASE_NOTES.md
> Release notes 0.5.0

- RELEASE_NOTES.md
- include/zcbor_decode.h
- include/zcbor_encode.h
- src/zcbor_decode.c
- src/zcbor_encode.c
- tests/cases/corner_cases.cddl
- tests/decode/test5_corner_cases/CMakeLists.txt
- tests/decode/test5_corner_cases/src/main.c
- tests/encode/test3_corner_cases/CMakeLists.txt
- tests/encode/test3_corner_cases/src/main.c
- tests/unit/test1_unit_tests/src/main.c
- zcbor/zcbor.py
That accept the int size as an argument. For use with enums.
Add tests.
> src: Add zcbor_int_decode() and zcbor_int_encode()

- .github/actions/prepare_and_run_tests/action.yaml
- .github/workflows/run-tests.yaml
- src/zcbor_encode.c
- tests/be_test.sh
- tests/cmake/test_template.cmake
- tests/decode/test1_suit_old_formats/testcase.yaml
- tests/decode/test2_suit/testcase.yaml
- tests/decode/test3_simple/testcase.yaml
- tests/decode/test5_corner_cases/testcase.yaml
- tests/decode/test7_suit9_simple/testcase.yaml
- tests/decode/test8_suit12/testcase.yaml
- tests/decode/test9_manifest14/testcase.yaml
- tests/encode/test1_suit/testcase.yaml
- tests/encode/test2_simple/testcase.yaml
- tests/encode/test3_corner_cases/testcase.yaml
- tests/encode/test4_senml/testcase.yaml
- tests/unit/test1_unit_tests/src/main.c
- tests/unit/test1_unit_tests/testcase.yaml
> Fix big-endian bug

- tests/scripts/run_tests.py
> run_tests.py: Refactor CLI tests to have less duplication

- src/zcbor_decode.c
- zcbor/zcbor.py
> Fix Coverity warnings

- include/zcbor_common.h
> zcbor_common.h: Fix docs for zcbor_update_state()

- .github/workflows/run-tests.yaml
- README.md
- tests/scripts/test_repo_files.py
- tests/scripts/test_versions.py
- tests/scripts/test_zcbor.py
- tests/test.sh
- Move tests around to new files.
- Clean up Github CI files.
- Add a new doc test (broken links).
> Rename and clean up Python tests

- tests/unit/test2_cpp/CMakeLists.txt
- tests/unit/test2_cpp/src/main.cpp
- zcbor/zcbor.py
> zcbor.py: Add support for C++ in generated code

- README.md
> README: Improve docs, particularly to help new users

- .github/actions/prepare_and_run_tests/action.yaml
- .github/workflows/run-tests.yaml
> run-tests.yaml: Update actions to newest versions

- include/zcbor_common.h
- src/zcbor_common.c
- tests/unit/test1_unit_tests/src/main.c
zcbor_compare_strings() and zcbor_header_len()
> zcbor_common: Add helper functions

- .github/workflows/run-tests.yaml
- tests/cases/pet0.yaml
- tests/fuzz/CMakeLists.txt
- tests/fuzz/test-afl.sh
Tested in https://github.com/NordicSemiconductor/zcbor/pull/301
> Fixes to fuzz tests

- src/zcbor_decode.c
Some places were missed by the first pass.
> Change the rest of uint_fast32_t usage to use size_t instead

- README.md
- RELEASE_NOTES.md
> Release notes for 0.7.0

- tests/cases/corner_cases.cddl
- tests/decode/test5_corner_cases/src/main.c
- tests/encode/test3_corner_cases/src/main.c
- zcbor/zcbor.py
> zcbor.py: Adjust the lower bound on negative numbers.

- zcbor/zcbor.py
Instead of calling with the raw pattern every time, make a cache of compiled regexes that just returns the precompiled regex on subsequent calls.
This speeds up execution.
> zcbor.py: Add a cache for compiled regex patterns

- zcbor/zcbor.py
The label regex was broken, this fixes it and replaces the all_type_regex system.
Only the union matching ('/') needs all_type_regex, but it really only needs the ones that match ranges, i.e. quotes and brackets. Refactor so it only uses this.
This speeds up execution.
> zcbor.py: Refactor the regex matching to fix label and remove all_types_regex

- include/zcbor_debug.h
- tests/unit/test1_unit_tests/src/main.c
> zcbor_debug.h: Add function for getting error string and printing it

- src/zcbor_decode.c
- src/zcbor_encode.c
- tests/unit/test3_float16/src/main.c
Some code was wrongly using CONFIG_BIG_ENDIAN, switch it back.
> Use ZCBOR_BIG_ENDIAN instead of CONFIG_BIG_ENDIAN

- README.md
> README: Fixed typos

- include/zcbor_common.h
- include/zcbor_encode.h
- src/zcbor_common.c
- src/zcbor_decode.c
Fixes https://github.com/NordicSemiconductor/zcbor/issues/348
> A few small changes

- src/zcbor_encode.c
> zcbor_encode: Simplify value_encode() by using the new zcbor_header_len

- RELEASE_NOTES.md
View at https://github.com/oyvindronningstad/zcbor/blob/release-notes-0.8.0/RELEASE_NOTES.md
> RELEASE_NOTES.md: Update release notes for 0.8.0

- samples/pet/src/pet_decode.c
- samples/pet/src/pet_encode.c
- zcbor/zcbor.py
> Fix range checks

- .github/workflows/run-tests.yaml
- tests/decode/test1_suit_old_formats/testcase.yaml
- tests/decode/test2_suit/testcase.yaml
- tests/decode/test3_simple/testcase.yaml
- tests/decode/test5_corner_cases/testcase.yaml
- tests/decode/test7_suit9_simple/testcase.yaml
- tests/decode/test8_suit12/testcase.yaml
- tests/decode/test9_manifest14/testcase.yaml
- tests/encode/test1_suit/testcase.yaml
- tests/encode/test2_simple/testcase.yaml
- tests/encode/test3_corner_cases/testcase.yaml
- tests/encode/test4_senml/testcase.yaml
- tests/test.sh
- tests/unit/test1_unit_tests/testcase.yaml
- tests/unit/test3_float16/testcase.yaml
> Replace all instances of native_posix_64 with native_posix/native/64

- .github/workflows/run-tests.yaml
- scripts/update_version.py
Two commits to prepare to release 0.9.0
> Prep 0.9.0

- samples/pet/src/pet_decode.c
- samples/pet/src/pet_encode.c
- zcbor/zcbor.py
which is added to the generated C file
> zcbor.py: Extract the logging of the result to a macro

- .gitignore
- zcbor/zcbor.py
Mostly to improve readability and debuggability.
Also removed some code that was completely unneeded.
> Various cleanup and refactoring

- zcbor/zcbor.py
> zcbor.py: Remove outdated assert statement

- samples/pet/src/pet_decode.c
- samples/pet/src/pet_encode.c
- zcbor/zcbor.py
To verify that the args are the right type.
> zcbor.py: Add dummy calls to function pointers

- src/zcbor_common.c
Replace pointer casting with a union type.
Some basic testing shows no change in code size.
Fixes #497
> zcbor_common.c: Fix strict-aliasing error in float conversion 16 <-> 32

- tests/scripts/doc_fail_cases/fail1.md
- tests/scripts/test_repo_files.py
Keep an internal known good urls list, and check the links in that list only at certain times.
Also fix a few things from the recent refactor.
> test_repo_files.py: Check fewer doc links
